[tools]
atlas = "0.32.0"
python = "3.13.0"

[tasks."dev:api"]
run = "uv run -- fastapi dev __init__.py"
dir = "apps/api"

[tasks."migrate:create"]
run = "atlas migrate diff --env sqlalchemy"
dir = "apps/api"

[tasks."migrate:apply"]
run = "atlas migrate apply --env sqlalchemy"
dir = "apps/api"
