/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearRouteImport } from './routes/$year_'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YearEventCodeRouteImport } from './routes/$year.$eventCode'

const YearRoute = YearRouteImport.update({
  id: '/$year_',
  path: '/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YearEventCodeRoute = YearEventCodeRouteImport.update({
  id: '/$year/$eventCode',
  path: '/$year/$eventCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$year': typeof YearRoute
  '/$year/$eventCode': typeof YearEventCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$year': typeof YearRoute
  '/$year/$eventCode': typeof YearEventCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$year_': typeof YearRoute
  '/$year/$eventCode': typeof YearEventCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$year' | '/$year/$eventCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$year' | '/$year/$eventCode'
  id: '__root__' | '/' | '/$year_' | '/$year/$eventCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YearRoute: typeof YearRoute
  YearEventCodeRoute: typeof YearEventCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$year_': {
      id: '/$year_'
      path: '/$year'
      fullPath: '/$year'
      preLoaderRoute: typeof YearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$year/$eventCode': {
      id: '/$year/$eventCode'
      path: '/$year/$eventCode'
      fullPath: '/$year/$eventCode'
      preLoaderRoute: typeof YearEventCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YearRoute: YearRoute,
  YearEventCodeRoute: YearEventCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
