name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Mise
        uses: jdx/mise-action@v2
      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile
      - name: Apply lint fixes
        run: mise run lint:fix
      - name: Apply formatter fixes
        run: mise run format:fix
      - name: Run autofix.ci
        uses: autofix-ci/action
        with:
          commit-message: 'refactor: apply automatic fixes'
