name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and test

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
      - name: Check
        run: vp check
      - name: Build
        run: vp build
      - name: Run Knip
        run: vp exec knip
