"""init

Revision ID: 281838b97f8b
Revises:
Create Date: 2025-05-05 18:10:14.733145

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "281838b97f8b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("events_year_code_index", table_name="events")
    op.create_index(op.f("ix_events_year"), "events", ["year", "code"], unique=True)
    op.drop_index("top_scores_event_internal_id_index", table_name="top_scores")
    op.drop_index("top_scores_score_index", table_name="top_scores")
    op.drop_index("top_scores_timestamp_index", table_name="top_scores")
    op.create_index(op.f("ix_top_scores_score"), "top_scores", ["score"], unique=False)
    op.create_index(
        op.f("ix_top_scores_timestamp"), "top_scores", ["timestamp"], unique=False
    )
    op.drop_constraint(
        "top_scores_event_internal_id_events_internal_id_fk",
        "top_scores",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "top_scores", "events", ["event_internal_id"], ["internal_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "top_scores", type_="foreignkey")
    op.create_foreign_key(
        "top_scores_event_internal_id_events_internal_id_fk",
        "top_scores",
        "events",
        ["event_internal_id"],
        ["internal_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_top_scores_timestamp"), table_name="top_scores")
    op.drop_index(op.f("ix_top_scores_score"), table_name="top_scores")
    op.create_index(
        "top_scores_timestamp_index", "top_scores", ["timestamp"], unique=False
    )
    op.create_index("top_scores_score_index", "top_scores", ["score"], unique=False)
    op.create_index(
        "top_scores_event_internal_id_index",
        "top_scores",
        ["event_internal_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_events_year"), table_name="events")
    op.create_index("events_year_code_index", "events", ["year", "code"], unique=True)
    # ### end Alembic commands ###
