"""init

Revision ID: 56d3e772f9f7
Revises:
Create Date: 2025-05-07 03:25:45.475180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56d3e772f9f7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("internal_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("code", sa.TEXT(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("first_code", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("internal_id"),
    )
    op.create_index(op.f("ix_events_year"), "events", ["year", "code"], unique=True)
    op.create_table(
        "matches",
        sa.Column("internal_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_number", sa.Integer(), nullable=False),
        sa.Column(
            "match_level",
            sa.Enum("QUALIFICATION", "PLAYOFF", name="match_level"),
            nullable=False,
        ),
        sa.Column("event_internal_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_internal_id"], ["events.internal_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("internal_id"),
        sa.UniqueConstraint("event_internal_id", "match_level", "match_number"),
    )
    op.create_table(
        "match_results",
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "winning_teams", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("match_internal_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_internal_id"], ["matches.internal_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("match_internal_id"),
    )
    op.create_index(
        op.f("ix_match_results_score"), "match_results", ["score"], unique=False
    )
    op.create_index(
        op.f("ix_match_results_timestamp"), "match_results", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_results_timestamp"), table_name="match_results")
    op.drop_index(op.f("ix_match_results_score"), table_name="match_results")
    op.drop_table("match_results")
    op.drop_table("matches")
    op.drop_index(op.f("ix_events_year"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
