"""unique_event_first_code

Revision ID: 78c0240fd395
Revises: 56d3e772f9f7
Create Date: 2025-05-07 20:54:01.287916

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "78c0240fd395"
down_revision: Union[str, None] = "56d3e772f9f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
