"""event_unique_constraint_fix

Revision ID: 7f8da7ce739c
Revises: 772a0d43f9bb
Create Date: 2025-05-08 02:55:08.848895

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7f8da7ce739c"
down_revision: Union[str, None] = "772a0d43f9bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_year", table_name="events")
    op.create_index("ix_events_year_code", "events", ["year", "code"], unique=True)
    op.create_index(
        "ix_events_year_first_code", "events", ["year", "first_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_year_first_code", table_name="events")
    op.drop_index("ix_events_year_code", table_name="events")
    op.create_index("ix_events_year", "events", ["year", "first_code"], unique=True)
    # ### end Alembic commands ###
