"""fix_match_pk

Revision ID: 9f4c64aaa398
Revises: 56c75226e590
Create Date: 2025-05-06 13:34:26.194094

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9f4c64aaa398"
down_revision: Union[str, None] = "56c75226e590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
