"""partial_matches_fix

Revision ID: d864e34b982a
Revises: 9f4c64aaa398
Create Date: 2025-05-06 23:10:29.308202

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d864e34b982a"
down_revision: Union[str, None] = "9f4c64aaa398"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches", "result_internal_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches", "result_internal_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
